### ISSUE TITLE
npx create-supertokens-app@latest experience on Ubuntu 22.04

### ISSUE THREAD

**Issue by reece** [supertokens/create-supertokens-app#41]
Here's my experience trying `npx create-supertokens-app@latest` 

1) Ubuntu 22.04 comes with node 12. `npx create-supertokens-app@latest` fails in a way that looks like supertokens is broken. Ideal solution: Support 22.04 because it's a common platform. At a minimum, include a note at https://supertokens.com/ about requirements. I'd rather have more instructions and something that works than an apparently simple command that doesn't.

2) After upgrading to nodejs 19 (per [these instructions](https://nodejs.org/en/download/package-manager/)), and then `npx create-supertokens-app@latest`, and configured like this:

```
? What is your app called? my-app
? Choose a frontend framework (Visit our documentation for integration with other frameworks): Vue.js
? Choose a backend framework (Visit our documentation for integration with other frameworks): Python (FastAPI)
? What type of authentication do you want to use? Social Login + Email Password
```

I get

```
snafu$ npm run start
⋮
app_data_dir=/home/reece/.local/share/virtualenv)
    added seed packages: pip==22.3, setuptools==65.5.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
sh: 1: source: not found
ERROR: "start:backend" exited with 127.
```

The problem here is that source is not a sh command. Editing package.json start:backend to use `.` (simply a period) in lieu of `source` allows the project to start. 

After that, I'm able to use social (google) and email registration auth.

**Comment by nkshah2** [comment]
Hi @reece,

Thanks for reporting this, we have released a fix in version 0.0.20. Feel free to reopen this issue if it still persists
