### ISSUE TITLE
Getting issue while creating Reactjs + GoLang app

### ISSUE THREAD

**Issue by shushantarora009** [supertokens/create-supertokens-app#45]
Hi

I tried creating Reactjs + Golang app, using 
npx create-supertokens-app@latest --recipe=passwordless

It got issue while creating backend app in Golang
Issue -  
Setup failed!
Error: go: malformed module path "'go-http'": invalid char '\''

while other app in React+python got created successfully,

Thanks

**Comment by sattvikc** [comment]
@shushantarora009 May I know which version of golang are you using?

**Comment by shushantarora009** [comment]
@sattvikc its go version go1.19 windows/amd64

**Comment by rishabhpoddar** [comment]
This has been fixed. Thanks for raising this PR
