### ISSUE TITLE
CLI does not work

### ISSUE THREAD

**Issue by djkelleher** [supertokens/create-supertokens-app#61]
Running the `npx create-supertokens-app@latest` command from the supertokens.com home page results in:

![image](https://github.com/supertokens/create-supertokens-app/assets/17990596/6c32301f-ceda-43cc-afef-57e21de2e6ae)

**Comment by rishabhpoddar** [comment]
Which OS, and version are you using? Also, which node version are you using?

**Comment by rishabhpoddar** [comment]
Keep in mind that we only support node 14+ for the CLI. So can you try upgrading your node version and trying again?

**Comment by djkelleher** [comment]
I'm using Ubuntu 22.04 (which is the latest long term support release).
Ubuntu's default software repository installs node 12. That was the issue. Thanks.
