### ISSUE TITLE
If the CLI takes a --fullstack option, why is nextjs option provided with --frontend option?

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/create-supertokens-app#78]
See the CLI command here: https://supertokens.com/docs/thirdpartyemailpassword/nextjs/app-directory/about

**Comment by nkshah2** [comment]
The `fullstack` flag may be mentioned in some comment but the CLI does not actually use it. If the frontend option provided by `--frontend` is a full stack framework (nextjs for example) it just skips the backend question

**Comment by rishabhpoddar** [comment]
Right. So it's just that the comment is wrong. Ok
