### ISSUE TITLE
Why does folder name validation need to validate if it's a valid npm package name?

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/create-supertokens-app#79]
This is said in this video: https://drive.google.com/file/d/1mKSHO1HWTgPufbBYLNF3Zh-GnuG5KuTE/view?usp=drive_link, at time 3:20.

**Comment by nkshah2** [comment]
We create a common package.json outside of the frontend and backend folders and then ask users to run `npm run start` or something similar to start the app. 

If the app name is not a valid package name, the start command will fail with "INVALID_PACKAGE_NAME" or something along those lines

**Comment by rishabhpoddar** [comment]
Right, but it's not necesary that the folder name (appname) should be equal to the package name right?

**Comment by nkshah2** [comment]
Nope, just needs to be a valid npm name for running

**Comment by rishabhpoddar** [comment]
The appname that the user providers is used for the folder name AND the package.json's package name. If it was only used for the folder name, then the user could enter any appname and the validation logic for checking if it's a valid npm package name would not apply.
